// Mocks generated by Mockito 5.2.0 from annotations
// in example/test/src/modules/auth/gui/presenters/login_ctrl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:example/src/modules/auth/data/repo/interface/auth_repo.dart'
    as _i2;
import 'package:example/src/modules/auth/data/repo/interface/auth_store_repo.dart'
    as _i3;
import 'package:example/src/modules/auth/domain/entities/login_response.dart'
    as _i4;
import 'package:example/src/modules/auth/domain/entities/params/login_param.dart'
    as _i7;
import 'package:example/src/modules/auth/domain/usecases/login_interactor.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAuthRepo_0 extends _i1.Fake implements _i2.AuthRepo {}

class _FakeAuthStoreRepo_1 extends _i1.Fake implements _i3.AuthStoreRepo {}

class _FakeLoginResponse_2 extends _i1.Fake implements _i4.LoginResponse {}

/// A class which mocks [LoginInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginInteractor extends _i1.Mock implements _i5.LoginInteractor {
  MockLoginInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepo get repo => (super.noSuchMethod(Invocation.getter(#repo),
      returnValue: _FakeAuthRepo_0()) as _i2.AuthRepo);
  @override
  _i3.AuthStoreRepo get storeRepo =>
      (super.noSuchMethod(Invocation.getter(#storeRepo),
          returnValue: _FakeAuthStoreRepo_1()) as _i3.AuthStoreRepo);
  @override
  _i6.Future<_i4.LoginResponse> call(_i7.LoginParam? param) =>
      (super.noSuchMethod(Invocation.method(#call, [param]),
              returnValue:
                  Future<_i4.LoginResponse>.value(_FakeLoginResponse_2()))
          as _i6.Future<_i4.LoginResponse>);
}
